# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pub_date'],
                'get_latest_by': 'pub_date',
                'db_table': 'newsdb',
            },
        ),
    ]
