# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170810_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date']},
        ),
    ]
