# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170810_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=750),
        ),
    ]
